dbfilename redis_queue.rdb
dir /home/baf/frappe/frappe-bench/config/pids
pidfile /home/baf/frappe/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/baf/frappe/frappe-bench/config/redis_queue.acl
